### ISSUE TITLE
Coding conventions

### ISSUE THREAD

**Issue by JustasGasparaitis** [Puskunalis/karma#13]
### We must establish a clear stand on our code conventions, before there is much more to refactor. I suggest the following:

_[C# Coding Conventions](https://docs.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/coding-conventions)_

Please provide feedback :)

**Comment by JustasGasparaitis** [comment]
Also:
[](https://github.com/dotnet/runtime/blob/main/docs/coding-guidelines/coding-style.md)

[](https://github.com/dotnet/codeformatter)

**Comment by MartynasStrazdas** [comment]
I agree on using your suggested code style standart.

**Comment by JustasGasparaitis** [comment]
Since Blazor uses HTML/CSS/C#, we also need to establish HTML/CSS coding guidelines.

I propose Google's style guide:
https://google.github.io/styleguide/htmlcssguide.html

If we all agree on these conventions, we can close the issue.
