### ISSUE TITLE
Remove charity functionality

### ISSUE THREAD

**Issue by MartynasStrazdas** [Puskunalis/karma#22]
Remove charity from database functionality. Tasks:
1. Button, which when pressed opens a modal with all charities
2. Backend to which when needed deletes specific charity listing from data base

**Comment by Puskunalis** [comment]
I suggest having this instead as an "admin page" issue where more such functionality would be available

**Comment by JustasGasparaitis** [comment]
I agree with @Puskunalis on the admin page, let's move it to issue #77
